//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOMPAdmin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public int Id { get; set; }
        public int MenuId { get; set; }
        public string Header { get; set; }
        public string Detail { get; set; }
        public string Picture { get; set; }
        public string PicDetails { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int Veg { get; set; }
        public int NonCustomized { get; set; }
        public Nullable<int> IsActive { get; set; }
        public string AvailableDay { get; set; }
        public Nullable<int> ShowDetails { get; set; }
        public string Varity { get; set; }
        public string DetailDinner { get; set; }
        public string ShowInBoth { get; set; }
        public string Calories { get; set; }
        public Nullable<int> OrderBy { get; set; }
    }
}
