//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOMPAdmin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int Id { get; set; }
        public string Header { get; set; }
        public string Detail { get; set; }
        public string ShowInBoth { get; set; }
        public Nullable<int> IsActive { get; set; }
        public string Picture { get; set; }
        public string HeaderCus { get; set; }
        public string DetailCus { get; set; }
    }
}
