//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOMPAdmin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> PlanId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> OrderStartDate { get; set; }
        public int PaymentDone { get; set; }
        public int IsLunch { get; set; }
        public Nullable<decimal> TotalPayment { get; set; }
        public Nullable<int> NonCustomized { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> RequestId { get; set; }
        public Nullable<int> pincode { get; set; }
        public Nullable<int> YourguyOrderId { get; set; }
    }
}
