//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOMPAdmin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> DaysInPlan { get; set; }
        public Nullable<int> ValidUpTo { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> DeliveryCharges { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> NightDeliveryCharges { get; set; }
    }
}
