//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOMPAdmin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLocation
    {
        public int Id { get; set; }
        public string Location { get; set; }
        public Nullable<int> CityDivisionID { get; set; }
        public Nullable<int> primeLocation { get; set; }
        public Nullable<int> pincode { get; set; }
    }
}
