//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOMPAdmin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string UserLoginID { get; set; }
        public string UserType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string mobile { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> WorkingSince { get; set; }
        public string picture { get; set; }
        public string STDCode { get; set; }
        public string LandLine { get; set; }
        public string WebsiteLink { get; set; }
        public string SocialLink { get; set; }
        public string Address { get; set; }
        public string AboutUs { get; set; }
        public string CompanyName { get; set; }
        public string CompanyLogo { get; set; }
        public string LandLine1 { get; set; }
        public string LandLine2 { get; set; }
    }
}
