//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOMP.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int Id { get; set; }
        public Nullable<int> TrnChrg { get; set; }
        public Nullable<int> DeliveryChrg { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public string Telephone { get; set; }
        public string email { get; set; }
        public Nullable<int> CashPickUp { get; set; }
        public Nullable<decimal> CashPickUpPercent { get; set; }
    }
}
