//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOMP.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingBilling
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string mobile { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string LandMark { get; set; }
        public string Pincode { get; set; }
        public string FirstNameB { get; set; }
        public string LastNameB { get; set; }
        public string mobileB { get; set; }
        public string CompanyNameB { get; set; }
        public string AddressB { get; set; }
        public string CityB { get; set; }
        public string LandMarkB { get; set; }
        public string PincodeB { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> RequestId { get; set; }
        public string State { get; set; }
        public string StateB { get; set; }
    }
}
